services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: viterbit-php
    working_dir: /app
    volumes:
      - .:/app:cached
    networks:
      - viterbit
    environment:
      - APP_ENV=dev
      - DATABASE_URL=postgresql://viterbit:viterbit@db:5432/viterbit?serverVersion=16&charset=utf8
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: viterbit-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/app:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - viterbit
    depends_on:
      - php

  db:
    image: postgres:16-alpine
    container_name: viterbit-db
    environment:
      POSTGRES_USER: viterbit
      POSTGRES_PASSWORD: viterbit
      POSTGRES_DB: viterbit
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - viterbit

  messenger:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: viterbit-messenger
    working_dir: /app
    volumes:
      - .:/app:cached
    networks:
      - viterbit
    environment:
      - APP_ENV=dev
      - DATABASE_URL=postgresql://viterbit:viterbit@db:5432/viterbit?serverVersion=16&charset=utf8
    depends_on:
      - db
    command: ["php", "bin/console", "ecotone:run", "enrichment", "-vv"]

volumes:
  pgdata:

networks:
  viterbit:
    driver: bridge
